SINGLE_FRAME_TIME = 0.03
HVH_DEBUG_OUTPUT = false

NIGHT_STALKER_UNIT_NAME = "npc_dota_hero_night_stalker"
SNIPER_UNIT_NAME = "npc_dota_hero_sniper"

SNIPER_INVALID  = -1
SNIPER_NONE     = 0
SNIPER_KARDEL   = 1
SNIPER_RIGGS    = 2
SNIPER_FLORAX   = 3
SNIPER_JEBBY    = 4

CONNECTION_STATE_NONE = 0
CONNECTION_STATE_BOT = 1
CONNECTION_STATE_PLAYER = 2
CONNECTION_STATE_DISCONNECTED = 3